name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PR Agent via Docker
        uses: docker://codiumai/pr-agent:latest
        env:
          OPENAI_KEY: ${{ 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 }}
          OPENAI_BASE_URL: https://openrouter.ai/api/v1
          LLM_PROVIDER: openai
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}